changelog:
  exclude:
    authors:
      - weblate
  categories:
    - title: 🚀 New
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - bug
    - title: 🐞 Fixed
      labels:
        - bug
    - title: ⚙️ Dependencies
      labels:
        - dependencies
