changelog:
  exclude:
    authors:
      - weblate
  categories:
    - title: 🚀 Features & Fixes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: ⚙️ Dependencies
      labels:
        - dependencies
