changelog:
  exclude:
    authors:
      - weblate
  categories:
    - title: 🚀 New
      labels:
        - feature
    - title: 🐞 Fixed
      labels:
        - bug
    - title: 🧱 Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - bug
          - feature
    - title: ⚙️ Dependencies
      labels:
        - dependencies
