blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/PaulWoitaschek/Voice/discussions
    about: Please use the discussions for feature ideas, upvotes and general ideas.
