name: "Post Build"
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: always()
      with:
        name: reports
        path: app/build/reports/**/*.html

    - name: Publish JUnit Report
      uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5
      if: always()
      with:
        report_paths: '**/test-results/**/TEST-*.xml'
