name: "Pre Build"
runs:
  using: "composite"
  steps:
    - name: Disable JDK Auto Download
      shell: bash
      run: |
        gradle_user_home="${GRADLE_USER_HOME:-$HOME/.gradle}"
        mkdir -p "$gradle_user_home"
        echo "org.gradle.java.installations.auto-download=false" >> "$gradle_user_home/gradle.properties"
    - id: jvm-version
      name: Extract Java Version
      shell: bash
      run: echo "version=$(awk -F'"' '/jvm-toolchain/ {print $2}' gradle/libs.versions.toml)" >> "$GITHUB_OUTPUT"
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: zulu
        java-version: ${{ steps.jvm-version.outputs.version }}
    - name: Bootstrap Gradle Memory
      shell: bash
      run: ./scripts/gradle_bootstrap.sh
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6
      with:
        cache-read-only: ${{ github.ref_name != github.event.repository.default_branch }}
